packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'docs'
  - 'examples/*'
  - 'e2e'
catalog:
  tsup: ^8.3.5
  typescript: ^5.7.2
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.1
