packages:
  - packages/*
  - docs
  - examples/*
  - e2e
catalogs:
  react18:
    '@types/react': ^18.3.20
    '@types/react-dom': ^18.3.6
    '@types/react-reconciler': 0.28.9
    react: ^18.3.1
    react-dom: ^18.3.1
    react-reconciler: 0.29.2
  react19:
    '@types/react': ^19.1.0
    '@types/react-dom': ^19.1.1
    '@types/react-reconciler': 0.28.9
    react: ^19.1.0
    react-dom: ^19.1.0
    react-reconciler: 0.31.0
catalog:
  '@types/react': ^18.3.20
  '@types/react-dom': ^18.3.6
  '@types/react-reconciler': 0.28.9
  react: ^18.3.1
  react-dom: ^18.3.1
  react-reconciler: 0.29.2
  tsup: ^8.4.0
  typescript: ^5.8.3
  remeda: ^2.21.2
